/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AttributeSelector {
  selector: string
  attribute: string
}

/** Extract specified attributes from HTML elements matching selectors. */
export declare function extractAttributes(
  html: string,
  options: ExtractAttributesOptions,
): Array<ExtractedAttributeResult>

export interface ExtractAttributesOptions {
  selectors: Array<AttributeSelector>
}

/** Extract the base href from HTML document. */
export declare function extractBaseHref(html: string, url: string): string

export interface ExtractedAttributeResult {
  selector: string
  attribute: string
  values: Array<string>
}

/** Extract all image URLs from HTML document. */
export declare function extractImages(html: string, baseUrl: string): Array<string>

/** Extract all links from HTML document. */
export declare function extractLinks(html?: string | undefined | null): Array<string>

/** Extract metadata from HTML document. */
export declare function extractMetadata(html?: string | undefined | null): Record<string, any>

/** Filter links based on crawling rules and constraints. */
export declare function filterLinks(data: FilterLinksCall): FilterLinksResult

export interface FilterLinksCall {
  links: Array<string>
  limit?: number
  maxDepth: number
  baseUrl: string
  initialUrl: string
  regexOnFullUrl: boolean
  excludes: Array<string>
  includes: Array<string>
  allowBackwardCrawling: boolean
  ignoreRobotsTxt: boolean
  robotsTxt: string
}

export interface FilterLinksResult {
  links: Array<string>
  denialReasons: Record<string, string>
}

/** Extract inner text content from HTML body. */
export declare function getInnerJson(html: string): string

/** Extract metadata from PDF file. */
export declare function getPdfMetadata(path: string): PdfMetadata

export interface ParsedSitemap {
  urlset?: SitemapUrlset
  sitemapindex?: SitemapIndex
}

/** Parse XML sitemap content into structured data. */
export declare function parseSitemapXml(xmlContent: string): ParsedSitemap

export interface PdfMetadata {
  numPages: number
  title?: string
}

/** Process sitemap XML and extract crawling instructions. */
export declare function processSitemap(xmlContent: string): SitemapProcessingResult

export interface SitemapEntry {
  loc: Array<string>
}

export interface SitemapIndex {
  sitemap: Array<SitemapEntry>
}

export interface SitemapInstruction {
  action: string
  urls: Array<string>
  count: number
}

export interface SitemapProcessingResult {
  instructions: Array<SitemapInstruction>
  totalCount: number
}

export interface SitemapUrl {
  loc: Array<string>
}

export interface SitemapUrlset {
  url: Array<SitemapUrl>
}

/** Transform and clean HTML content based on provided options. */
export declare function transformHtml(opts: TransformHtmlOptions): string

export interface TransformHtmlOptions {
  html: string
  url: string
  includeTags: Array<string>
  excludeTags: Array<string>
  onlyMainContent: boolean
  omceSignatures?: Array<string>
}
