/* auto-generated by NAPI-RS */
/* eslint-disable */

// scrape_url types, generated by ts-rs from apps/api/native/src/scrape_url.
// Regenerate with `pnpm ts-bindings` in apps/api/native.
// prettier-ignore
export declare namespace ScrapeUrl {
  export type Action = { "type": "wait" } & { milliseconds?: number, selector?: string } | { "type": "click", selector: string, all?: boolean, } | { "type": "screenshot", fullPage?: boolean, quality?: number | null, viewport?: ScreenshotOptionsViewport | null, } | { "type": "write", text: string, } | { "type": "press", key: string, } | { "type": "scroll", direction?: ActionScrollDirection, selector?: string | null, } | { "type": "scrape" } | { "type": "executeJavascript", script: string, } | { "type": "pdf", landscape?: boolean, scale?: number, format?: ActionPdfFormat, };
  export type ActionPdfFormat = "A0" | "A1" | "A2" | "A3" | "A4" | "A5" | "A6" | "Letter" | "Legal" | "Tabloid" | "Ledger";
  export type ActionScrollDirection = "up" | "down";
  export type AttributesOptions = { selectors: Array<AttributesSelector>, };
  export type AttributesSelector = { selector: string, attribute: string, };
  export type BrandingMode = "auto" | "fast" | "standard";
  export type BrandingOptions = { mode?: BrandingMode | null, };
  export type ChangeTrackingMode = "json" | "git-diff";
  export type ChangeTrackingOptions = { prompt?: string | null, schema?: JsonValue | null, modes?: Array<ChangeTrackingMode>, tag?: string | null, };
  export type DeterministicJsonOptions = { prompt?: string | null, schema?: JsonValue | null, };
  export type Document = { markdown?: string, html?: string, rawHtml?: string, rawBase64?: string, links?: Array<string>, images?: Array<string>, screenshot?: string, audio?: string, video?: string, extract?: JsonValue, json?: JsonValue, summary?: string, answer?: string, highlights?: string, pages?: Array<PdfPage>, blocks?: Array<PdfBlockItem>, warning?: string, attributes?: Array<DocumentAttribute>, actions?: RawPageActions, metadata: DocumentMetadata, };
  export type DocumentAttribute = { selector: string, attribute: string, values: Array<string>, };
  export type DocumentMetadata = { title?: string, scrapeId: string, sourceURL: string, url: string, statusCode: number, numPages?: number, totalPages?: number, contentType: string, timezone?: string, proxyUsed: ScrapeProxy, cacheState: DocumentMetadataCacheState, cachedAt?: string, indexId?: string, creditsUsed?: number, concurrencyLimited: boolean, concurrencyQueueDurationMs?: number, postprocessorsUsed?: Array<string>, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
  export type DocumentMetadataCacheState = "hit" | "miss";
  export type Format = "markdown" | { type: "markdown" } | "html" | { type: "html" } | "rawHtml" | { type: "rawHtml" } | "rawBase64" | { type: "rawBase64" } | "links" | { type: "links" } | "images" | { type: "images" } | "summary" | { type: "summary" } | "json" | ({ type: "json" } & JsonOptions) | "deterministicJson" | ({ type: "deterministicJson" } & DeterministicJsonOptions) | "changeTracking" | ({ type: "changeTracking" } & ChangeTrackingOptions) | "screenshot" | ({ type: "screenshot" } & ScreenshotOptions) | ({ type: "attributes" } & AttributesOptions) | "branding" | ({ type: "branding" } & BrandingOptions) | "product" | { type: "product" } | "menu" | { type: "menu" } | ({ type: "question" } & QuestionOptions) | ({ type: "highlights" } & HighlightsOptions) | ({ type: "query" } & QueryOptions) | "audio" | { type: "audio" } | "video" | { type: "video" };
  export type HighlightsOptions = { query: string, };
  export type InternalOptions = { crawlId?: string | null, priority?: number | null, v0CrawlOnlyUrls?: boolean, v0DisableJsDom?: boolean, disableSmartWaitCache?: boolean, isBackgroundIndex?: boolean, urlInvisibleInCurrentCrawl?: boolean, unnormalizedSourceURL?: string | null, saveScrapeResultToGCS?: boolean, bypassBilling?: boolean, zeroDataRetention?: boolean, v1OriginalFormat?: V1OriginalFormat | null, agentIndexOnly?: boolean, isPreCrawl?: boolean, };
  export type JavascriptActionContent = { type: string, value: JsonValue, };
  export type JsonOptions = { prompt?: string | null, schema?: JsonValue | null, checkPromptInjection?: boolean | null, };
  export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;
  export type Parser = "pdf" | ({ type: "pdf" } & PdfOptions) | "image" | { type: "image" };
  export type PdfBlockItem = { id: string, type: string, label: string | null, bbox: [number, number, number, number] | null, content: string, markdownSpan: [number, number] | null, readingOrder: number, source: string | null, confidence: PdfBlockItemConfidence, };
  export type PdfBlockItemConfidence = { layout: number | null, ocr: number | null, };
  export type PdfMode = "auto" | "fast" | "ocr";
  export type PdfOptions = { mode?: PdfMode, maxPages?: number | null, 
  /**
   * Include physical per-page markdown alongside document markdown.
   */
  pages?: boolean, 
  /**
   * Include per-page types layout blocks (bounding boxes, block types, reading order) alongside document markdown.
   */
  blocks?: boolean, 
  /**
   * Join PDF pages in `document.markdown` with `\n\n---\n\n<!-- page N -->\n\n` where N is the 1-based physical page
   * of the content that follows. Markers appear between pages only (no leading marker for page 1), and numbering may
   * skip pages merged by cross-page stitching — callers that need every physical page should use `pages: true` instead.
   * No new response field.
   */
  pageMarkers?: boolean, };
  export type PdfPage = { page: number, markdown: string, };
  /**
   * PDF classification carried by `SCRAPE_PDF_OCR_REQUIRED`.
   */
  export type PdfType = "TextBased" | "Scanned" | "ImageBased" | "Mixed";
  export type ProxyMode = "basic" | "stealth" | "auto";
  export type QueryMode = "freeform" | "directQuote";
  export type QueryOptions = { prompt: string, mode?: QueryMode, };
  export type QuestionOptions = { question: string, };
  export type RawPageActions = { screenshots?: Array<string>, scrapes?: Array<ScrapeActionContent>, javascriptReturns?: Array<JavascriptActionContent>, pdfs?: Array<string>, };
  export type ScrapeActionContent = { url: string, html: string, };
  /**
   * Structured payload of a rejected `scrapeUrl` promise, discriminated by
   * `code`. Codes shared with TS `error.ts` carry the fields its `deserialize`
   * reads; the Rust-specific codes below them also carry a `message`.
   */
  export type ScrapeError = { "code": "CRAWL_DENIAL", reason: string, } | { "code": "SCRAPE_LOCKDOWN_CACHE_MISS" } | { "code": "AGENT_INDEX_ONLY" } | { "code": "SCRAPE_PDF_OCR_REQUIRED", pdfType: PdfType, } | { "code": "SCRAPE_SITE_ERROR", errorCode: string, } | { "code": "SCRAPE_SSL_ERROR", skipTlsVerification: boolean, } | { "code": "SCRAPE_DNS_RESOLUTION_ERROR", hostname: string, } | { "code": "SCRAPE_UNSUPPORTED_FILE_ERROR", reason: string, } | { "code": "SCRAPE_ACTION_ERROR", errorCode: string, } | { "code": "SCRAPE_PROXY_SELECTION_ERROR" } | { "code": "SCRAPE_ALL_ENGINES_FAILED", fallbackList: Array<string>, message: string, } | { "code": "SCRAPE_ACTIONS_NOT_SUPPORTED", message: string, } | { "code": "SCRAPE_JSON_CONTENT_TOO_LARGE", message: string, } | { "code": "UNKNOWN_ERROR", message: string, } | { "code": "SCRAPE_RELIABLE_RETRIEVAL_ERROR", proxy: ProxyMode, message: string, } | { "code": "SCRAPE_INSECURE_CONNECTION_ERROR", message: string, } | { "code": "SCRAPE_INVALID_URL_ERROR", message: string, } | { "code": "SCRAPE_PDF_FETCH_FAILED", message: string, } | { "code": "SCRAPE_PAGE_LOAD_FAILED", message: string, } | { "code": "SCRAPE_UNCLASSIFIED_ENGINE_ERROR", engine: string, error: string, message: string, } | { "code": "SCRAPE_ENGINE_UNAVAILABLE", engine: string, status: number, message: string, } | { "code": "SCRAPE_NOT_SUPPORTED", feature: string, message: string, } | { "code": "SCRAPE_INVALID_INPUT", argument: string, message: string, } | { "code": "SCRAPE_PANIC", message: string, };
  export type ScrapeOptions = { formats: Array<Format>, headers?: { [key in string]: string }, includeTags?: Array<string>, excludeTags?: Array<string>, onlyMainContent: boolean, onlyCleanContent: boolean, timeout?: number | null, waitFor?: number | null, mobile: boolean, parsers?: Array<Parser>, actions?: Array<Action>, location?: ScrapeOptionsLocation, skipTlsVerification?: boolean | null, removeBase64Images: boolean, blockAds: boolean, proxy: "basic" | "stealth" | "enhanced" | "auto", maxAge?: number | null, minAge?: number | null, storeInCache: boolean, lockdown: boolean, profile?: ScrapeOptionsProfile | null, __searchPreviewToken?: string | null, __experimental_omce?: boolean, __experimental_omceDomain?: string | null, __experimental_engpicker?: boolean, __forceFirePDF?: boolean, };
  export type ScrapeOptionsLocation = { country?: string, languages?: Array<string>, };
  export type ScrapeOptionsProfile = { name: string, saveChanges?: boolean, };
  export type ScrapeProxy = "basic" | "stealth";
  export type ScreenshotOptions = { fullPage?: boolean, quality?: number | null, viewport?: ScreenshotOptionsViewport | null, };
  export type ScreenshotOptionsViewport = { width: number, height: number, };
  /**
   * The format a v1 request asked for; extracted data is kept under that field name.
   */
  export type V1OriginalFormat = "extract" | "json";
  export type ScrapeErrorCode = ScrapeError["code"];
}
