import os
from google import genai
from PIL import Image
from io import BytesIO


class GeminiClient:
    def __init__(self, api_key: str, model: str = "gemini-2.5-flash-image-preview"):
        if not api_key:
            raise ValueError("Gemini API key is required.")
        self.client = genai.Client(api_key=api_key)
        self.model = model

    def edit_image(self, image_bytes: bytes, prompt: str, high_quality: bool = True) -> bytes:
        """
        Send image + prompt to Gemini Flash API and return edited image bytes.
        """
        if high_quality:
            prompt += """
            QUALITY:
            - Ultra high resolution
            - Sharp details
            - Rich color depth
            - Professional/artistic quality
            """

        try:
            image = Image.open(BytesIO(image_bytes))
        except Exception as e:
            raise ValueError(f"Invalid image bytes provided: {e}")

        try:
            response = self.client.models.generate_content(
                model=self.model,
                contents=[prompt, image]
            )
        except Exception as e:
            raise RuntimeError(f"Gemini API request failed: {e}")

        parts = []
        try:
            parts = [p.inline_data.data for p in response.candidates[0].content.parts if p.inline_data]
        except Exception:
            pass

        if not parts:
            # fallback: return original image if Gemini fails
            return image_bytes
        return parts[0]

    def generate_image(self, prompt: str, high_quality: bool = True) -> bytes:
        """
        Generate an image from text using Gemini Flash.
        """
        if high_quality:
            prompt += """
            QUALITY:
            - Ultra high resolution
            - Sharp details
            - Rich color depth
            - Professional/artistic quality
            """

        try:
            response = self.client.models.generate_content(
                model=self.model,
                contents=prompt
            )
        except Exception as e:
            raise RuntimeError(f"Gemini API request failed: {e}")

        parts = []
        try:
            parts = [p.inline_data.data for p in response.candidates[0].content.parts if p.inline_data]
        except Exception:
            pass

        if not parts:
            raise RuntimeError("No image generated by Gemini.")
        return parts[0]
