//! Renders the TypeScript types of everything crossing the `scrapeUrl` napi
//! boundary. `pnpm ts-bindings` writes them to `scrape-url.d.ts`, which
//! `napi build` prepends to `index.d.ts` (`napi.dtsHeaderFile`). Rerun it after
//! changing any of these types.

use std::collections::BTreeMap;

use ts_rs::{Config, TS, TypeVisitor};

use super::{
  document::Document,
  error::ScrapeErrorPayload,
  options::{InternalOptions, ScrapeOptions},
};

struct Collector<'a> {
  cfg: &'a Config,
  decls: BTreeMap<String, String>,
  clashes: Vec<String>,
}

impl TypeVisitor for Collector<'_> {
  fn visit<T: TS + 'static + ?Sized>(&mut self) {
    if T::output_path().is_none() {
      return;
    }

    let name = T::ident(self.cfg);
    let decl = format!(
      "{}export {}",
      T::docs().unwrap_or_default(),
      T::decl(self.cfg)
    );
    if let Some(existing) = self.decls.get(&name) {
      if *existing != decl {
        self.clashes.push(name);
      }
      return;
    }

    self.decls.insert(name, decl);
    T::visit_dependencies(self);
  }
}

/// Contents of `scrape-url.d.ts`.
pub fn render_scrape_url_ts_bindings() -> Result<String, String> {
  let cfg = Config::new().with_large_int("number");
  let mut collector = Collector {
    cfg: &cfg,
    decls: BTreeMap::new(),
    clashes: Vec::new(),
  };
  collector.visit::<ScrapeOptions>();
  collector.visit::<InternalOptions>();
  collector.visit::<Document>();
  collector.visit::<ScrapeErrorPayload>();
  if !collector.clashes.is_empty() {
    return Err(format!(
      "different types render as {}",
      collector.clashes.join(", ")
    ));
  }

  let mut out = String::from(
    "/* auto-generated by NAPI-RS */\n/* eslint-disable */\n\n\
     // scrape_url types, generated by ts-rs from apps/api/native/src/scrape_url.\n\
     // Regenerate with `pnpm ts-bindings` in apps/api/native.\n\
     // prettier-ignore\n\
     export declare namespace ScrapeUrl {\n",
  );
  for decl in collector.decls.values() {
    for line in decl.lines() {
      out.push_str("  ");
      out.push_str(line);
      out.push('\n');
    }
  }
  out.push_str("  export type ScrapeErrorCode = ScrapeError[\"code\"];\n}\n");
  Ok(out)
}
