name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        # defaults:
        #   run:
        #     working-directory: './apps/api'
        steps:
          - name: 'Check out the repository'
            uses: actions/checkout@v2  # 这一步是确保您的仓库代码被检出到运行器上

          - name: 'Log in to Alibaba Cloud ACR'
            run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} --username ${{ secrets.ACR_USERNAME }} --password-stdin

          - name: 'Set up Docker Buildx'
            uses: docker/setup-buildx-action@v1
 
          # - name: 'Build and Push api Image for Multiple Platforms'
          #   working-directory: './apps/api'
          #   run: |
          #     acr_image="${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_SPACE }}/firecrawl:latest"
          #     docker buildx build --platform linux/amd64,linux/arm64 -t $acr_image . --push
          
          - name: 'Build and Push playwright Image for Multiple Platforms'
            working-directory: './apps/playwright-service'
            run: |
              acr_image="${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_SPACE }}/playwright:latest"
              docker buildx build --platform linux/amd64,linux/arm64 -t $acr_image . --push


          # - name: 'Build Inventory Image'
          #   run: |
          #     docker build . --tag zhiyan/firecrawl:latest
          #     docker push zhiyan/firecrawl:latest
          # - name: 'Checkout GitHub Action'
          #   uses: actions/checkout@main

          # - name: 'Login to GitHub Container Registry'
          #   uses: docker/login-action@v1
          #   with:
          #     registry: ghcr.io
          #     username: ${{github.actor}}
          #     password: ${{secrets.GITHUB_TOKEN}}

          # - name: 'Build Inventory Image'
          #   run: |
          #     docker build . --tag ghcr.io/mendableai/firecrawl:latest
          #     docker push ghcr.io/mendableai/firecrawl:latest
